### ISSUE TITLE
[ Enhancement ] Add an option to disable "lone pone" keyword

### ISSUE THREAD

**Issue by zneix** [LonelessCodes/trixiebot#14]
**Before submitting I have**
- [x] Double checked existing Issues/Pull Requests for a similar suggestion.

**Describe the change you would like to see**
From what I've checked, there's no way to disable that keyword in a config and disabling it can be actually useful.

**Why should we change it that way?**
Not everyone wants to have their channels clogged with images while having a conversation, especially when there's no cooldown or anything which would prevent bot from being spammy. Most of the members/bots are not allowed to post images anyway and we want it to stay that way.

**Additional context**
Kinda offtopic, but you seem to have an unnecessary `\` in your issue templates (near the checklist).

**Comment by LonelessCodes** [comment]
Disabled the keyword in 13c6378 (slipped into this commit accidentally but I'll be leaving it there). This keyword was created when Trixie was still a lil bean for friend servers, but since I'm not so active on Discord any more I'll just be taking it out for lack of a better way to handle it.

This command specifically is better off as a custom command bound to one or more specific servers. Apropos, custom commands should be reworked as well.
The way keyword commands are integrated in Trixie currently is not very elegant and generally just bothers me. I created an issue on the topic here: #17. 

Thank you for creating issues on these topics. Sorry I got to these so late - I only picked development back up last week.
